---
- name: Generate kubeadm join command and token
  ansible.builtin.command: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  changed_when: false

- name: Upload certificates and generate certificate key for HA
  ansible.builtin.command: kubeadm init phase upload-certs --upload-certs
  register: kubeadm_upload_certs
  changed_when: false

- name: Extract certificate key
  ansible.builtin.set_fact:
    # The actual hex key is printed on the very last line of the output
    cert_key: "{{ kubeadm_upload_certs.stdout_lines | last | trim }}"

- name: Set base join command as a fact
  ansible.builtin.set_fact:
    join_command: "{{ kubeadm_join_cmd.stdout | trim }}"
