- name: Ensure /etc/modules-load.d/k8s.conf exists
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
    mode: '0644'

- name: Load overlay kernel module
  community.general.modprobe:
    name: overlay
    state: present

- name: Load br_netfilter kernel module
  community.general.modprobe:
    name: br_netfilter
    state: present
