[masters]
master-1 ansible_host=192.168.122.245
master-2 ansible_host=192.168.122.134
master-3 ansible_host=192.168.122.106

[workers]
worker-1 ansible_host=192.168.122.253

[k8s_cluster:children]
masters
workers

[all:vars]
ansible_user=ansible
ansible_ssh_private_key_file=~/.ssh/k8s_ansible_key
ansible_python_interpreter=/usr/bin/python3
