---
- name: Configure Node Prerequisites for Kubernetes
  hosts: k8s_cluster
  become: true
  tasks:
    - name: Disable Swap
      include_tasks: tasks/01_disable_swap.yaml

    - name: Configure Kernel Modules
      ansible.builtin.import_tasks: tasks/02_kernel_modules.yaml

    - name: Set Sysctl Parameters
      include_tasks: tasks/03_sysctl_params.yaml

    - name: Install Container Runtime (containerd)
      include_tasks: tasks/04_containerd.yaml

    - name: Install Kubernetes Binaries
      include_tasks: tasks/05_k8s_binaries.yaml

    - name: Run validation Script
      ansible.builtin.import_tasks: tasks/06_run_validation.yaml

  handlers:
    - name: Restart containerd
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        enabled: true

    - name: Update GRUB
      ansible.builtin.command: update-grub
